version: '3'

services: 

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_DATABASE: ${PERSISTENCE_USER}
      - MYSQL_ROOT_PASSWORD: ${PERSISTENCE_PASSWORD}

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: wesleywillians/nginx:prod
    ports: 
      - "8080:80"

  app:
    build: 
      context: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    ports: 
      - "3000:3000"
    environment: 
      - PERSISTENCE_USER: ${PERSISTENCE_USER}
      - PERSISTENCE_PASSWORD: ${PERSISTENCE_PASSWORD}