version: '3'

services: 

  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: $PERSISTENCE_DATABASE
      MYSQL_USER: $PERSISTENCE_USER
      MYSQL_PASSWORD: $PERSISTENCE_PASSWORD
      MYSQL_ROOT_PASSWORD: $PERSISTENCE_ROOT_PASSWORD

  nginx:
    build: ./nginx
    ports: 
      - "8080:8080"

  app:
    build: ./node
    environment:
      PERSISTENCE_HOST: ${PERSISTENCE_HOST}
      PERSISTENCE_USER: ${PERSISTENCE_USER}
      PERSISTENCE_PASSWORD: ${PERSISTENCE_PASSWORD}