version: '3'

services: 

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: $PERSISTENCE_USER
      MYSQL_ROOT_PASSWORD: $PERSISTENCE_PASSWORD

  nginx:
    build: ./nginx
    ports: 
      - "8080:8080"

  app:
    build: ./node
    ports: 
      - "3000:3000"
    environment: 
      PERSISTENCE_USER: ${PERSISTENCE_USER}
      PERSISTENCE_PASSWORD: ${PERSISTENCE_PASSWORD}